language: elixir

otp_release:
  - 20.2
before_install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - set -e
  - MIX_ENV=test mix format --check-formatted
  - set +e
  - set -e
  - mix credo --strict
  - set +e
  - mix coveralls.json
after_script:
  - bash <(curl -s https://codecov.io/bash)
  - bash .scripts/inch_report.sh

matrix:
  include:
  - elixir: "1.5.3"
    script:
      - mix coveralls.json
  - elixir: "1.6.5"

notifications:
  email:
    on_success: never
    recipients:
      - ananya95+travis@gmail.com
